{% set name = "request" %}
{% set version = "2.85.1" %}
{% set sha256 = "eb58a387985159bfbb0bbdd47d70621d23bdc72a88827b2e2fde11e988cbeed5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/request/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g request
  requires:
    - nodejs
   

about:
  home: https://github.com/request/request
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Simplified HTTP request client.'
  description: |
    Simplified HTTP request client. 
  doc_url: https://github.com/request/request
  dev_url: https://github.com/request/request

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
