travis:
  secure:
    BINSTAR_TOKEN: eIxeuGhgcKmAo9llfNSUhEReTOOZP6Sk81VxWOaofBAJikN1ESbnpa1nH3sNKycpSWvHKE2KQdS/vu+65ia9o1CLFhefN0IbNkWz+Q79+w6swWHMui9e4wIWNXVaXDLAEA2ay/DsnH9saM96MlSqNBwpekAmPvNeDPt33lnMkHHjY/OACvEohkZNorrsQKUN85f6LVy/xkxx9dNyx8PE5ckzKjaf45avsRPyZg7ISOEhiiP2SSbhPe+U8AUDl0XjlFNQMk6UUimRNnIQPz9GylFoI2dGLDIYm2GX/q+fQZ6gWrvo4ZdjYdV1nuALl/2iK1xYQCLXx9sSrUClg0bcOiW1F23LaandOdARM2kzA9d+S6E7DmKrPWw/U8CIOR6xDWkVEccl2OtK7vZYX4kBjLltdtbAATS/2LHrdd7L87463TyJAOFq5N0Y3nNmXGzXdjpGopkGh5XAyrDTsDEyWR2qCMhl4xDYHv5pyuhdminT/bthKdh0fvRVOuXb0qXsgm8qcTldzd/l8dVMa6+kUSKWAxXnTd5y87PW4Fwi0HAZW2uZvd/FyzeL6SwVC6FGyzWR+oJDeOxlGLSwbqdKgDr0xtFu98AUiuc64qhNJg8TUo8IelMQhq4pYdtYa3CWF4Mfg3dVrxG9wtkJA/ryXmr/opPAh0FrLvyLp1O0OFo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
