travis:
  secure:
    BINSTAR_TOKEN: T/MIjjxYZk1QFz7RHCfyEavGhYIqvXCb6UQObGMegMNhw5cvPJ+1Owj5zzjSHzuyk0GEcn7xnsx+qzr2UpXdMQCGNKUO2vQmligUcKZ6E7MpajRwo4bFHtmQ+nZZ+yZIFSDe3XRgQ2rn9pvf8TapVNGjrl6G0Aeb7WlXlBqxUtvgbQjTMFgonPHY1ifQMDX5TQ3m/ArN+7K0r2+dd67fyGO+yySsvUXYHTNWvBiCTJjoaAgcwx1EtWq+N5TXjBS6KgHauQ6lM8kFXa1JMcYIaulMTI0fAUCcagM3lO2WVs9rGXSkTUQtx8Zan2Ggxe5VL/VxHaE91Y2eH4dJhTV2GSZSacivaKsD7VqZK1cdZV8CaayWll7d94ZHMnM+4m7suRqKbKgx58XERYUyNCqaYiWARC6P5LyjvdfI0ph3DmdRP3TwC6TS9XRqQC3Jx6rrktzkar0SD50yZi85G6N7RpbjxEiO0nx9rwCrM1VhDSPi6E7vpy+KtewlO+2nFpST/1F7FAwGoJM+xYa6finYY08MnDV76z0rhxmUVGI+fQ5fQi9dvV9IrLDOwjfRolfBHy7TFyAUW2FV9yLNEG9i7vRxDPt3+x1ufb95tBISAmjzzRLR2y73JCWkwejISdT+34bUJ90HbJOw6v1kEvVG6A4JEV6MX4eMX4CdPkREAME=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
