travis:
  secure:
    BINSTAR_TOKEN: yCYADQFF+wk+zaXGp3yV8Pw4NSRZeMHy0wWGIU16IzD2f8Lf835QXXCMaIT25xvvI8endJB2oNKkOTS+wcYPQ+JTVtb4wf/x+pm5pteynDJnP/VOTAOrwSYdnXXAeybj9iYfEcwQw1cn23vZY0cfFhFjsYORcMQ+ZjCuYfHA8/1qiRQXY4A5yceDs444nrO7T401PP9fPa9wUy4NE7ZARYTXKlMI0V1/YHMWxdNd9XQjaZwo+DRU7gHqIQc2aZJ5Q+tc/6ucDL0ShWmejmivRlW+LT2DkkNCrR25buCCE+8w4QPvgPL0HSHaP9GTJHPR60zenp9AX4Pfik9Q7Bb2C5vdsQ5bjsZhAW6WMj13u5XB93TpKRCxxgELtwb1rWLaItlhtYfzCGOG17r12J+hX+Wz+avl7tBaWYK7LAMq1WId1sIAS/t2E6xbLT+SPj9caAzvDaD/i27UJCdqyv4QtOs6uHvC3N91MMyKpKLZgi+rtr5ajjzY0jlw2X2t45VP/QBRynydOXaTdqdtgGtgy4mJAErylQtRyJPN3aK4RlLg3+2k15XKcWMojmu8gfZmNUnpdM4z6h//xLe1D7mzAF8+t2ZZgO3uNIq2e0qG2Wwp4rVpTzTys+Y7MDtrlt5WTyGytIU+SnwcUAjUabH9pGcJkwSUxMrpmEnSVw7v4qs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
